name: Backend-AWS
on: push
jobs:
    backend-aws:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build the image
              run: docker build -t 173971919437.dkr.ecr.us-west-2.amazonaws.com/backend:${{ github.sha }} backend
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-2
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
            - name: Push the image
              run: docker push 173971919437.dkr.ecr.us-west-2.amazonaws.com/backend:${{ github.sha }}
