name: Client
on:
    push:
        paths:
            - 'packages/client/**'
            - '.github/workflows/client.yml'
jobs:
    client:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.11.0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.14.2
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Build Bundle
              run: pnpm --filter client build
            - name: Run Test
              run: pnpm --filter client test
