name: Firstload
on:
    push:
        paths:
            - 'firstload/**'
            - '.github/workflows/firstload.yml'
jobs:
    firstload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.2
                  registry-url: https://registry.npmjs.org
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache
              uses: actions/cache@v2.1.6
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install main dependencies
              run: yarn
            # - name: Run tests
            #   run: cd firstload && yarn test
            - name: Build Bundle
              run: cd firstload && yarn build
            - name: Confirm new version
              run: cd firstload && python3 ../scripts/compare.py -s firstload
            - name: Publish
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta'
              run: cd firstload && yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
