name: Frontend
on:
    push:
        branches:
            - '**'
            - '!master'
        paths:
            - 'packages/frontend/**'
            - '.github/workflows/frontend.yml'
jobs:
    changes:
        runs-on: ubuntu-latest
        # Set job outputs to values from filter step
        outputs:
            gql: ${{ steps.filter.outputs.gql }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      gql:
                        - 'packages/frontend/src/graph/operators/query.gql'
                        - 'packages/frontend/src/graph/operators/mutation.gql'
    generate-check:
        needs: [changes]
        if: needs.changes.outputs.gql == 'true'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.11.0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.14.2
                  registry-url: https://registry.npmjs.org
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: copy frontend
              run: |
                  mkdir tmp
                  cp -a packages/frontend/. tmp/
            - name: Generate code
              run: pnpm --filter frontend run gql:nowatch
            - name: Diff Check
              run: diff -r packages/frontend/src/graph tmp/src/graph
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.11.0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.14.2
                  registry-url: https://registry.npmjs.org
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm --filter frontend --prefer-offline
            - name: Runs linting
              run: pnpm --filter frontend test
            - name: Build Bundle
              run: export NODE_OPTIONS='--max-old-space-size=7168' && CI=false pnpm --filter frontend run build
