name: highlight-run/next
on:
    push:
        paths:
            - 'highlight-next/**'
            - '.github/workflows/highlight-next.yml'
jobs:
    highlight-next:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.0
                  registry-url: https://registry.npmjs.org
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache
              uses: actions/cache@v2.1.6
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install main dependencies
              run: yarn
            - name: Build @highlight-run/node dependency
              run: yarn workspace @highlight-run/node build
            - name: Build Bundle
              run: yarn workspace @highlight-run/next build
            - name: Confirm new version
              run: cd highlight-next && python3 ../scripts/compare.py -s highlight-next
            - name: Publish
              if: github.ref == 'refs/heads/master'
              run: |
                  echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml;
                  yarn workspace @highlight-run/node npm publish --access public;
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
