name: highlight-run/next
on:
    push:
        paths:
            - 'packages/highlight-next/**'
            - '.github/workflows/highlight-next.yml'
jobs:
    highlight-next:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.14.0
                  registry-url: https://registry.npmjs.org
                  cache: 'pnpm'
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Install dependencies
              run: pnpm install
            # - name: Run tests
            #   run: pnpm --filter highlight-next test
            - name: Build Bundle
              run: pnpm --filter highlight-next run build
            - name: Confirm new version
              run: cd packages/highlight-next && python3 ../../scripts/compare.py -s highlight-next
            - name: Publish
              if: github.ref == 'refs/heads/master'
              run: pnpm --filter highlight-next publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
