name: Ruby SDK

on:
    push:
        branches: []
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'sdk/highlight-ruby/**'
            - '.github/workflows/ruby.yml'
    merge_group:

jobs:
    build:
        name: Ruby SDK
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./sdk/highlight-ruby/highlight
        steps:
            - uses: actions/checkout@v3
            - name: Install Ruby 2.6
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.6'
            - name: Install dependencies
              run: bundle install
            - name: Test
              run: bundle exec rake
            - name: Rubocop
              run: bundle exec rubocop
            - name: Publish to RubyGems
              uses: dorny/paths-filter@v2
              id: filter
              with:
                  filters: |
                      version-file-changed:
                        - lib/highlight/version.rb
              if: steps.changes.output.version-file-changed == 'true'
              run: |
                  echo "publish step"
              env:
                  RUBYGEMS_API_KEY: '${{secrets.RUBYGEMS_API_KEY}}'
