name: CI

on:
    push:
        branches: ['master']
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Build and Test Yarn Turbo Monorepo
        timeout-minutes: 15
        runs-on: ubuntu-latest
        # configures Turborepo Remote Caching
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache
              uses: actions/cache@v2.1.6
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn

            - name: Build & Test
              run: yarn test:all
